GET https://staging.paysintech.dev/api/v1/users/me
//GET https://staging.paysintech.dev/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY0ZTc2NDk3ZGE3Y2ZhOWNjMDkwZDcwZTIyNDQ2YTc0YjVjNTBhYTkiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoidGVzdDEyMzQ1IiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3RlY2hzYWxhcmllcyIsImF1ZCI6InRlY2hzYWxhcmllcyIsImF1dGhfdGltZSI6MTY1NDE1NzE2NiwidXNlcl9pZCI6Ikh0cDkzaXhuU3NZR1N3N3BsVWt6ZlpQaXZrNTIiLCJzdWIiOiJIdHA5M2l4blNzWUdTdzdwbFVremZaUGl2azUyIiwiaWF0IjoxNjU0MTU3MTY2LCJleHAiOjE2NTQxNjA3NjYsImVtYWlsIjoidGVzdDEyMzQ1QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QxMjM0NUBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ZsnAAy6nvdsO3CpgYo4PJZDFKYvPFOIwDGod-G26hcfd91u2nozfyfAWO59SokCVqC3pZ7pwL8D4OWHjJJ8LM8wKppHFR4_yMWPoISloVpfv0dQeqtQUr2HZOms3OozAKmADQf92aHUtW1w3saK_voTt8FU2ma1HtyHYrHht0Ek9ehmnNblrKU5fQT8tHD7EA1QEx8zsSWo-263VDzVkHjoGYXq1_U4gkXhK5bHVthRyrukDM2HFPKYteJq6eZ0IkSJaJDTNHNH0FsJf3zZ9yYw6dNjRXyY3vQVjaMbT_42nAi5w9xrt3DpwOOgoTPHe7i2fXiX_Qhk5GbDJR-lQug