POST http://localhost:8080/api/v1/users/register
//POST https://staging.paysintech.dev/api/v1/users/register
Content-Type: application/json

{
  "username": "test12345",
  "email": "test12345@example.com",
  "password": "12345678"
}