version: "3.9"
services:
  backend:
    build: api/
    ports:
      - "8080:8080"
    environment:
      DATABASE_NAME: paysintech
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: paysintech
      DATABASE_PASSWORD: password123
    depends_on:
      - db_migration
    links:
      - db
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: paysintech
      POSTGRES_PASSWORD: password123

  db_migration:
    build: migration/
    command: liquibase update --changelog-file=changelog/changelog.xml --defaultsFile=changelog/liquibase.docker.properties
    environment:
      DATABASE_NAME: paysintech
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: paysintech
      DATABASE_PASSWORD: password123
    links:
      - db
