version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_NAME: techsalaries
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: techsalaries
      DATABASE_PASSWORD: password123
    links:
      - db
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: techsalaries
      POSTGRES_PASSWORD: password123
